"""
This type stub file was generated by pyright.
"""

import numpy as np
import warnings
from .settings import close, get_figures, log_directory, verbosity
from .utils import calc_options, interactive_options, zoom_options
from .core import Fractal, Fractal_plotter, _Pillow_figure
from .perturbation import PerturbationFractal
from .log import set_log_handlers

__author__ = ...
__license__ = ...
__version__ = ...
if verbosity < 3:
    ...
