"""
This type stub file was generated by pyright.
"""

import numba

logger = ...
class Postproc_batch:
    def __init__(self, fractal, calc_name) -> None:
        """
        Container for several postprocessing objects (instances of `Postproc`)
        which share the same Fractal & calculation (*calc_name*)
        
        It is usefull to have such container to avoid re-calculation of data
        that can be shared between several post-processing objects.
        
        Parameters
        ==========
        fractal : fractalshades.Fractal instance
            The shared fractal object
        calc_name : str 
            The string identifier for the shared calculation
        """
        ...
    
    @property
    def postnames(self): # -> dict_keys[Any, Any]:
        ...
    
    def add_postproc(self, postname, postproc): # -> None:
        """
        Add successive postprocessing and ensure they share identical
        *fractal* & *calc_name*

        Parameters
        ==========
        postname : str
            The string identifier that will be associated with this
            post-processing object
        postproc : `Postproc` instance
            The post-processing object to be added

        Notes
        =====
        .. warning::
            A Postproc can only be added to one batch.
        """
        ...
    
    def set_chunk_data(self, chunk_slice, chunk_mask, c_pix, Z, U, stop_reason, stop_iter, complex_dic, int_dic, termination_dic): # -> None:
        ...
    
    def update_context(self, chunk_slice, context_update): # -> None:
        ...
    
    def clear_chunk_data(self, chunk_slice): # -> None:
        """ Temporary data shared by postproc items when iterating a given
        chunk """
        ...
    


class Postproc:
    """
    Abstract base class for all postprocessing objects.
    """
    field_count = ...
    def __init__(self) -> None:
        """ Filter None values : removing them from post_dic.
        """
        ...
    
    def link_batch(self, batch): # -> None:
        """
        Link to Postproc group
        :meta private:
        """
        ...
    
    @property
    def fractal(self):
        ...
    
    @property
    def calc_name(self):
        ...
    
    @property
    def raw_data(self):
        ...
    
    @property
    def context(self):
        ...
    
    @property
    def state(self):
        ...
    
    @property
    def holomorphic(self): # -> bool:
        ...
    
    def ensure_context(self, chunk_slice, key):
        """
        Check that the provided context contains the expected data
        :meta private:
        """
        ...
    
    def __getitem__(self, chunk_slice):
        """ Subclasses should implement
        """
        ...
    
    def get_zn(self, Z, complex_dic):
        ...
    
    def get_dzndc(self, Z, c_pix, complex_dic): # -> _Array[tuple[int], float64] | tuple[_Array[tuple[int], float64], _Array[tuple[int], float64], _Array[tuple[int], float64], _Array[tuple[int], float64]] | tuple[Any, Any, Any, Any]:
        """ Returns the derivatives taking into account potential scaling
        due to transfomation
        """
        ...
    
    def get_std_cpt(self, c_pix):
        """ image pixel -> c mapping
        """
        ...
    


class Raw_pp(Postproc):
    def __init__(self, key, func=...) -> None:
        """A raw postproc provide direct access to the res data stored (memmap)
        during calculation. (Similar to what does `Fractal_array`  but 
        here within a `Postproc_batch`)

        Parameters
        ==========
        key: str
            The raw data key. Should be one of the *complex_codes*,
            *int_codes*, *termination_codes* for this calculation.
        func: None | callable | a str of variable x (e.g. "np.sin(x)")
            will be applied as a pre-processing step to the raw data if not
            `None`
        """
        ...
    
    def __getitem__(self, chunk_slice): # -> tuple[Any, dict[Any, Any]]:
        """ Returns the raw array, with self.func applied if not None """
        ...
    


class Continuous_iter_pp(Postproc):
    def __init__(self, kind=..., d=..., a_d=..., M=..., epsilon_cv=..., floor_iter=...) -> None:
        """Return a continuous iteration number: this is the iteration count at
        bailout, plus a fractionnal part to allow smooth coloring.
        Implementation based on potential, for details see:

            - *On Smooth Fractal Coloring Techniques*,
              **Jussi Härkönenen**, Abo University, 2007

        Parameters
        ==========
        kind :  str "infinity" | "convergent" | "transcendent"
            the classification of potential function.
        d : None | int
            degree of polynome d >= 2 if kind = "infinity"
        a_d : None | float
            coeff of higher order monome if kind = "infinity"
        M : None | float
            High number corresponding to the criteria for stopping iteration
            if kind = "infinity"
        epsilon_cv : None | float
            Small number corresponding to the criteria for stopping iteration
            if kind = "convergent"
        floor_iter : int
            If not 0, a shift will be applied and floor_iter become the 0th 
            iteration.
            Used to avoids loss of precision (banding) for very large iteration
            numbers, usually above several milions. For 
            reference, the largest integer that cannot be accurately
            represented with a float32 is > 16 M), banding will start to be
            noticeable before.

        Notes
        =====
        .. note::
            Usually it is not needed to set any parameter ; 
            if a parameter ``param``
            is not provided, it will defaut to the attribute of 
            the fractal with name ``potential_<param>``, which should be the 
            recommended value.
        """
        ...
    
    @property
    def potential_dic(self): # -> dict[Any, Any]:
        """ 
        Returns the potential parameters properties
           priority order :
               1) user input to Continuous_iter_pp constructor
               2) fractal (or fractal 'state') defaut potential attributes
                   ("potential_" + prop)
               3) default to None if 1) and 2) fail. """
        ...
    
    def __getitem__(self, chunk_slice): # -> tuple[Any, dict[str, dict[Any, Any] | Incomplete | Any | None]]:
        """  Returns the real Iteration number
        """
        ...
    


class Fieldlines_pp(Postproc):
    def __init__(self, n_iter=..., swirl=..., endpoint_k=...) -> None:
        """
        Return a continuous orbit-averaged angular value, allowing to reveal
        fieldlines. Implementation based on [#f2]_. The averaging orbit starts
        at the computed `zn_orbit` field if it exists, otherwise at the exit 
        `zn` value, and is truncated after `n_iter` iterations.

        Fieldlines approximate the external rays which are very important
        in the study of the Mandelbrot set and more generally in
        holomorphic dynamics. 

        .. [#f2] *On Smooth Fractal Coloring Techniques*,
          **Jussi Härkönenen**, Abo University, 2007

        Parameters
        ==========
        n_iter :  int > 0
            the number of orbit points used for the averageing
        swirl : float between -1. and 1.
            adds a random dephasing effect between each successive orbit point
        endpoint_k : float > 0.
            A geometric serie is used for scaling individual orbit points,
            this parameters is the ratio between the last and the first scaling
            (For an arithmetic mean over the truncated orbit, use 1.)

        Notes
        =====
        .. note::
            The Continuous iteration number  shall have been calculated before
            in the same `Postproc_batch`
        """
        ...
    
    def __getitem__(self, chunk_slice): # -> tuple[_Array[tuple[int], float64] | Any, dict[Any, Any]]:
        """  Returns the post arr
        """
        ...
    


class DEM_normal_pp(Postproc):
    field_count = ...
    def __init__(self, kind=...) -> None:
        """ 
        Return the 2 components of the distance estimation method derivative
        (*normal map*).
        This postproc is normally used in combination with a
        `fractalshades.colors.layers.Normal_map_layer`

        Parameters
        ==========
        `kind`:  str "potential" | "Milnor" | "convergent"
            if "potential" (default) DEM is base on the potential.
            For Mandelbrot power 2, "Milnor" option is also available which 
            gives slightly different results (sharper edges).
            Use "convergent" for convergent fractals...

        Notes
        =====
        .. note::
            The Continuous iteration number shall have been calculated before
            in the same `Postproc_batch`
            If kind="Milnor", the following raw complex fields
            must be available from the calculation:
            "zn", "dzndc", "d2zndc2"
        """
        ...
    
    @property
    def x(self): # -> XYCoord_wrapper_pp:
        """ Postproc for the real part """
        ...
    
    @property
    def y(self): # -> XYCoord_wrapper_pp:
        """ Postproc for the imag part """
        ...
    
    def __getitem__(self, chunk_slice): # -> tuple[Any, None]:
        """  Returns the normal as a complex (x, y, 1) is the normal vec
        """
        ...
    


class XYCoord_wrapper_pp(Postproc):
    def __init__(self, pp_2d, coord) -> None:
        """ Helper class to split one complex Postproc into 2 real & imag parts
        """
        ...
    
    @property
    def context_getitem_key(self):
        ...
    
    def __getitem__(self, chunk_slice): # -> tuple[Any, dict[Any, Any]]:
        ...
    
    def link_sibling(self, sibling): # -> None:
        """ The other coord """
        ...
    


class DEM_pp(Postproc):
    field_count = ...
    def __init__(self, px_snap=...) -> None:
        """ 
        Return a distance estimation of the pixel to the fractal set.
        
        Parameters
        ==========
        `px_snap`:  None | float
            If not None, pixels at a distance from the fractal lower
            than `px_snap` (expressed in image pixel) will be snapped to 0.

        Notes
        =====
    
        .. note::
            The Continuous iteration number  shall have been calculated before
            in the same `Postproc_batch`
        """
        ...
    
    def __getitem__(self, chunk_slice): # -> tuple[NDArray[Incomplete] | Any, dict[Any, Any]]:
        """  Returns the DEM - """
        ...
    


class Attr_normal_pp(Postproc):
    field_count = ...
    def __init__(self) -> None:
        """ 
        Return the 2 components of the cycle attractivity derivative (*normal
        map*).
        This postproc is normally used in combination with a
        `fractalshades.colors.layers.Normal_map_layer`

        Notes
        =====
        .. note::
            The following complex fields must be available from a previously
            run calculation:

                - "attractivity"
                - "order" (optionnal)
        """
        ...
    
    @property
    def x(self): # -> XYCoord_wrapper_pp:
        """ Postproc for the real part """
        ...
    
    @property
    def y(self): # -> XYCoord_wrapper_pp:
        """ Postproc for the imag part """
        ...
    
    def __getitem__(self, chunk_slice): # -> tuple[NDArray[float64], None]:
        """  Returns the normal as a complex (x, y, 1) is the normal vec
        """
        ...
    


class Attr_pp(Postproc):
    field_count = ...
    def __init__(self, scale_by_order=...) -> None:
        """ 
        Return the cycle attractivity
        
        Parameters
        ==========
        scale_by_order : bool
            If True return the attractivity divided by ccyle order (this
            allows more realistic 3d-view exports)

        Notes
        =====
        .. note::
            The following complex fields must be available from a previously
            run calculation:

                - "attractivity"
                - "order" (optionnal)
        """
        ...
    
    def __getitem__(self, chunk_slice): # -> tuple[Any, dict[Any, Any]]:
        """  Returns the normal as a complex (x, y, 1) is the normal vec
        """
        ...
    


class Fractal_array:
    def __init__(self, fractal, calc_name, key, func=..., inv=...) -> None:
        """
        Class which provide a direct access to the res data stored (memory
        mapping)  during calculation.

        One application, it can be passed as a *subset* parameter to most
        calculation models, e.g. : `fractalshades.models.Mandelbrot.base_calc`

        Parameters
        ==========
        fractal : `fractalshades.Fractal` derived class
            The reference fracal object
        calc_name : str 
            The calculation name
        key :
            The raw data key. Should be one of the *complex_codes*,
            *int_codes*, *termination_codes* for this calculation.
        func: None | callable | a str of variable x (e.g. "np.sin(x)")
              will be applied as a pre-processing step to the raw data if not
              `None` - use of str form is recommended
        """
        ...
    
    @staticmethod
    def parse_func(func): # -> Any | None:
        ...
    
    def __reduce__(self): # -> tuple[type[Self], tuple[Any, Any, Any, Any | None, bool], None, None, None, None]:
        """ Enable standard Python serialization mechanism
        """
        ...
    
    def __getitem__(self, chunk_slice): # -> Any | ndarray[_AnyShape, dtype[Any]]:
        """ Returns the raw array, with self.func applied if not None """
        ...
    
    def __invert__(self): # -> Fractal_array:
        """ Allows use of the ~ notation 'ala numpy' """
        ...
    
    def __eq__(self, other) -> bool:
        """ Equality testing, useful when pickling / unpickling"""
        ...
    


@numba.njit(nogil=True, fastmath=False)
def apply_df(df, c_pix, dzndc): # -> _Array[tuple[int], float64]:
    ...

@numba.njit(nogil=True, fastmath=False)
def apply_dfBS(dfBS, c_pix, dXdA, dXdB, dYdA, dYdB): # -> tuple[_Array[tuple[int], float64], _Array[tuple[int], float64], _Array[tuple[int], float64], _Array[tuple[int], float64]]:
    ...

@numba.njit(nogil=True, fastmath=True)
def Continuous_iter_pp_infinity(zn, d, a_d, M): # -> Any:
    ...

@numba.njit(nogil=True, fastmath=True)
def Continuous_iter_pp_convergent(zn, eps, attractivity, z_star): # -> Any:
    ...

@numba.njit(nogil=True, fastmath=True)
def cm_H0(x):
    ...

@numba.njit(nogil=True, fastmath=True)
def cm_H1(x):
    ...

@numba.njit(nogil=True, fastmath=True)
def cm_H2(x):
    ...

@numba.njit(nogil=True, fastmath=True)
def cm_H3(x):
    ...

@numba.njit(nogil=True, fastmath=True)
def Fieldlines_pp_infinity(c_pt, zn, nu_frac, k_arr, phi_arr, zn_iterate, is_backward, backshift, n): # -> _Array[tuple[int], float64]:
    ...

@numba.njit(nogil=True, fastmath=True)
def Fieldlines_pp_infinity_BS(c_pt, xn, yn, nu_frac, k_arr, phi_arr, xnyn_iterate, is_backward, backshift, n): # -> _Array[tuple[int], float64]:
    ...

