"""
This type stub file was generated by pyright.
"""

import pathlib
# from fractalshades import colors

class Perturbation_mandelbrot:

    def __init__(self, out_dir: str | pathlib.Path) -> None: ...

    def zoom(
        self,
        *,
        precision: int,
        x: str,
        y: str,
        dx: str,
        nx: int,
        xy_ratio: float,
        # colormap: colors.Fractal_colormap,
        # max_iter: int,
        # calc_name: str,
        theta_deg: float,
        projection: str,
    ) -> None: ...

    def calc_std_div(
        self,
        *,
        calc_name: str,
        subset: str | None,  # TODO: type??
        max_iter: int,
        M_divergence: float,
        epsilon_stationnary: float,
        BLA_eps: float,
        interior_detect: bool,
        calc_orbit: bool,
    ) -> None: ...
